[package]
name = "backend-core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
dotenv = "0.15.0"
mongodb = "3.4.1"
qdrant-client = "1.16.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
